import { AuthProvider } from '@/context/authContext';
import { monserrat } from '@/styles/fonts';
import '@/styles/globals.css';

export const metadata = {
  title: 'CRM - MotoRenting',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="es">
        <body className={`${monserrat.className} antialiased`}>{children}</body>
      </html>
    </AuthProvider>
  );
}
