export const Roles = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  COORDINADOR: 'COORDINADOR',
  ASESOR: 'ASESOR',
  AUXILIAR: 'AUXILIAR',
  EJECUTIVO_FINANCIERO: 'EJECUTIVO_FINANCIERO',
  COORDINADOR_DE_ENTREGA: 'COORDINADOR_DE_ENTREGA',
};
