'use client';

export const customers = [
  {
    id: 1,
    name: 'Juan Pérez',
    email: 'juanperez@email.com',
    phone: '3101234567',
    address: 'Calle 123',
    city: 'Bogotá',
    document: '123456789',
    advisor: 'Maria Manrrique',
    state: 'INTENTANDO CONTACTAR',
    comments: [
      {
        date: '2025-08-10 - 9:00 am',
        description: 'Cliente contactado por primera vez',
      },
      {
        date: '2025-08-10 - 9:00 am',
        description: 'Cliente contactado por primera vez',
      },
      {
        date: '2025-08-10 - 9:00 am',
        description: 'Cliente contactado por primera vez',
      },
      {
        date: '2025-08-10 - 9:00 am',
        description: 'Cliente contactado por primera vez',
      },
      {
        date: '2025-08-10 - 9:00 am',
        description: 'Cliente contactado por primera vez',
      },
      {
        date: '2025-08-10 - 9:00 am',
        description: 'Cliente contactado por primera vez',
      },
    ],
  },
  {
    id: 2,
    name: 'María López',
    email: 'marialopez@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Jorge Espinosa',
    state: 'INTENTANDO CONTACTAR',
    comments: [
      {
        date: '2025-08-10 - 9:00 am',
        description: 'Cliente contactado por primera vez',
      },
    ],
  },
  {
    id: 3,
    name: 'Enrique Montalve',
    email: 'enrique@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Sin Asignar',
    state: 'Sin Contactar',
    comments: [
      {
        date: '',
        description: '',
      },
    ],
  },
  {
    id: 4,
    name: 'Jorge lopez',
    email: 'jorgelopez@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Sin Asignar',
    state: 'Sin Contactar',
    comments: [
      {
        date: '',
        description: '',
      },
    ],
  },
  {
    id: 5,
    name: 'Sofia Montalve',
    email: 'sofiamontalve@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Sin Asignar',
    state: 'Sin Contactar',
    comments: [
      {
        date: '',
        description: '',
      },
    ],
  },
  {
    id: 6,
    name: 'Manuel Quiara',
    email: 'jorgelopez@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Maria Manrrique',
    state: 'INTENTANDO CONTACTAR',
    comments: [
      {
        date: '2025-08-10 - 9:00 am',
        description: 'Cliente contactado por primera vez',
      },
    ],
  },
  {
    id: 7,
    name: 'Yeison Montalve',
    email: 'sofiamontalve@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Sin Asignar',
    state: 'Sin Contactar',
    comments: [
      {
        date: '',
        description: '',
      },
    ],
  },
  {
    id: 8,
    name: 'Cristina lopez',
    email: 'jorgelopez@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Sin Asignar',
    state: 'Sin Contactar',
    comments: [
      {
        date: '',
        description: '',
      },
    ],
  },
  {
    id: 9,
    name: 'Oscar Montalve',
    email: 'sofiamontalve@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Jorge Espinosa',
    state: 'INTENTANDO CONTACTAR',
    comments: [
      {
        date: '2025-08-10 - 9:00 am',
        description: 'Cliente contactado por primera vez',
      },
    ],
  },
  {
    id: 10,
    name: 'Juan Pérez',
    email: 'juanperez@email.com',
    phone: '3101234567',
    address: 'Calle 123',
    city: 'Bogotá',
    document: '123456789',
    advisor: 'Maria Manrrique',
    state: 'INTENTANDO CONTACTAR',
    comments: [
      {
        date: '2025-08-10 - 9:00 am',
        description: 'Cliente contactado por primera vez',
      },
    ],
  },
  {
    id: 11,
    name: 'María López',
    email: 'marialopez@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Jorge Espinosa',
    state: 'INTENTANDO CONTACTAR',
    comments: [
      {
        date: '2025-08-10 - 9:00 am',
        description: 'Cliente contactado por primera vez',
      },
    ],
  },
  {
    id: 12,
    name: 'Enrique Montalve',
    email: 'enrique@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Sin Asignar',
    state: 'Sin Contactar',
    comments: [
      {
        date: '',
        description: '',
      },
    ],
  },
  {
    id: 13,
    name: 'Jorge lopez',
    email: 'jorgelopez@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Sin Asignar',
    state: 'Sin Contactar',
    comments: [
      {
        date: '',
        description: '',
      },
    ],
  },
  {
    id: 14,
    name: 'Sofia Montalve',
    email: 'sofiamontalve@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Sin Asignar',
    state: 'Sin Contactar',
    comments: [
      {
        date: '',
        description: '',
      },
    ],
  },
  {
    id: 15,
    name: 'Manuel Quiara',
    email: 'jorgelopez@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Maria Manrrique',
    state: 'INTENTANDO CONTACTAR',
    comments: [
      {
        date: '2025-08-10 - 9:00 am',
        description: 'Cliente contactado por primera vez',
      },
    ],
  },
  {
    id: 16,
    name: 'Yeison Montalve',
    email: 'sofiamontalve@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Sin Asignar',
    state: 'Sin Contactar',
    comments: [
      {
        date: '',
        description: '',
      },
    ],
  },
  {
    id: 17,
    name: 'Cristina lopez',
    email: 'jorgelopez@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Sin Asignar',
    state: 'Sin Contactar',
    comments: [
      {
        date: '',
        description: '',
      },
    ],
  },
  {
    id: 18,
    name: 'Oscar Montalve',
    email: 'sofiamontalve@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Jorge Espinosa',
    state: 'INTENTANDO CONTACTAR',
    comments: [
      {
        date: '2025-08-10 - 9:00 am',
        description: 'Cliente contactado por primera vez',
      },
    ],
  },
  {
    id: 19,
    name: 'Juan Pérez',
    email: 'juanperez@email.com',
    phone: '3101234567',
    address: 'Calle 123',
    city: 'Bogotá',
    document: '123456789',
    advisor: 'Maria Manrrique',
    state: 'INTENTANDO CONTACTAR',
    comments: [
      {
        date: '2025-08-10 - 9:00 am',
        description: 'Cliente contactado por primera vez',
      },
    ],
  },
  {
    id: 20,
    name: 'María López',
    email: 'marialopez@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Jorge Espinosa',
    state: 'INTENTANDO CONTACTAR',
    comments: [
      {
        date: '2025-08-10 - 9:00 am',
        description: 'Cliente contactado por primera vez',
      },
    ],
  },
  {
    id: 21,
    name: 'Enrique Montalve',
    email: 'enrique@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Sin Asignar',
    state: 'Sin Contactar',
    comments: [
      {
        date: '',
        description: '',
      },
    ],
  },
  {
    id: 22,
    name: 'Jorge lopez',
    email: 'jorgelopez@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Sin Asignar',
    state: 'Sin Contactar',
    comments: [
      {
        date: '',
        description: '',
      },
    ],
  },
  {
    id: 23,
    name: 'Sofia Montalve',
    email: 'sofiamontalve@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Sin Asignar',
    state: 'Sin Contactar',
    comments: [
      {
        date: '',
        description: '',
      },
    ],
  },
  {
    id: 24,
    name: 'Manuel Quiara',
    email: 'jorgelopez@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Maria Manrrique',
    state: 'INTENTANDO CONTACTAR',
    comments: [
      {
        date: '2025-08-10 - 9:00 am',
        description: 'Cliente contactado por primera vez',
      },
    ],
  },
  {
    id: 25,
    name: 'Yeison Montalve',
    email: 'sofiamontalve@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Sin Asignar',
    state: 'Sin Contactar',
    comments: [
      {
        date: '',
        description: '',
      },
    ],
  },
  {
    id: 26,
    name: 'Cristina lopez',
    email: 'jorgelopez@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Sin Asignar',
    state: 'Sin Contactar',
    comments: [
      {
        date: '',
        description: '',
      },
    ],
  },
  {
    id: 27,
    name: 'Oscar Montalve',
    email: 'sofiamontalve@email.com',
    phone: '3129876543',
    address: 'Carrera 456',
    city: 'Medellín',
    document: '987654321',
    advisor: 'Jorge Espinosa',
    state: 'INTENTANDO CONTACTAR',
    comments: [
      {
        date: '2025-08-10 - 9:00 am',
        description: 'Cliente contactado por primera vez',
      },
    ],
  },
];
